package com.example.messagequeueexception;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import com.google.android.material.textfield.TextInputEditText;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        TextInputEditText textInputEditText = findViewById(R.id.input);
        textInputEditText.setText("\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non ante vel tellus dignissim facilisis ut nec velit. Sed nunc nisl, congue nec quam quis, tincidunt convallis purus. Aliquam erat volutpat. Vivamus vitae neque facilisis dolor varius sodales id et lacus. Donec condimentum sem ac ligula condimentum, ut feugiat lectus finibus. Integer vel accumsan purus. Cras commodo fermentum nibh. Nullam at nibh quam. Pellentesque pharetra facilisis nisi, eu sollicitudin diam hendrerit id. Donec quis ex eget neque sagittis laoreet nec a libero. Nullam vitae felis iaculis, elementum lacus in, mattis erat. Nam lacinia varius hendrerit.\n" +
                "\n" +
                "Vestibulum pretium, magna sed vulputate dignissim, libero lectus pellentesque erat, sed varius erat est ac odio. Nulla nec nisl lobortis, ullamcorper augue eu, venenatis dolor. Quisque et magna a dui ornare sollicitudin. Aenean posuere, ipsum sed posuere blandit, elit justo imperdiet orci, eget dapibus odio lectus eu ex. Sed et viverra dolor. Praesent non maximus dui, vel malesuada quam. Nam egestas quis neque non cursus. Nunc lobortis cursus tincidunt. Nam ullamcorper cursus ligula sit amet venenatis. Aliquam erat volutpat. Nulla vitae viverra ipsum, at laoreet magna. Donec vehicula commodo leo. Nunc auctor pulvinar ipsum, nec posuere nibh porta non. Etiam eget sodales odio, sed ultrices lacus. Aliquam erat volutpat.\n" +
                "\n" +
                "Ut maximus neque ac pretium placerat. Vestibulum dolor turpis, elementum a ex nec, lobortis commodo mauris. Ut scelerisque est non diam convallis suscipit. Ut velit nisi, sollicitudin vestibulum pretium quis, feugiat eget mauris. Etiam diam quam, luctus eget pretium vel, volutpat eu justo. In convallis nibh ex. Sed elit magna, scelerisque sit amet enim vel, maximus ornare nunc. Maecenas imperdiet sollicitudin velit, a feugiat odio placerat eget. Donec id tempor libero. Sed euismod nec ante sit amet pharetra. Phasellus euismod porttitor porttitor. Nunc tempus sed ligula faucibus lobortis.\n" +
                "\n" +
                "Aliquam erat volutpat. Sed vel ornare nunc. Mauris semper eros sodales est maximus, non viverra velit pulvinar. Proin eu ex gravida, pellentesque nulla eu, elementum erat. Donec nisi risus, ullamcorper et sem et, hendrerit rhoncus nisl. Vestibulum placerat turpis interdum lorem rutrum, eget tincidunt libero tempor. Quisque urna massa, commodo venenatis consequat quis, maximus et nunc.\n" +
                "\n" +
                "Sed sodales eu diam ac luctus. Nulla eu dui nunc. Suspendisse aliquam tellus consectetur mauris porta, et varius diam feugiat. Phasellus fermentum lorem sit amet lorem cursus porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus molestie lorem sed leo fringilla, at pulvinar risus mollis. In quis elit nisi. Suspendisse scelerisque ut nibh sed varius. Duis consectetur nisi arcu, non vehicula ex ornare sit amet. Nunc in massa malesuada, egestas eros sed, imperdiet dui. Pellentesque ac nisl laoreet, maximus lacus in, blandit urna. Mauris ullamcorper orci non interdum dignissim. Morbi pulvinar dui id magna placerat viverra. Nulla facilisi.\n" +
                "\n" +
                "Vivamus rutrum aliquam rhoncus. Vestibulum vestibulum finibus tellus, vitae volutpat augue fringilla ut. In felis quam, ultricies id elit et, finibus molestie risus. Nam eget elit et diam porttitor fringilla. Vivamus tempor tellus in posuere fringilla. Vivamus mollis enim egestas felis lobortis iaculis. Mauris in urna lacus. Nam porta elit elit, eu porttitor ipsum finibus ac. Sed sit amet elit massa. Suspendisse facilisis vestibulum lorem, in posuere erat auctor ac. Duis dignissim et ex quis semper. Sed vel felis sapien. Praesent commodo et odio vel sollicitudin. Etiam facilisis nulla diam, et tempor risus pellentesque ut.\n" +
                "\n" +
                "Nullam dignissim est felis, vestibulum interdum justo malesuada et. Donec non neque porta, mollis magna vel, efficitur ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nulla sit amet efficitur aliquam. Vivamus gravida imperdiet nisi, ac convallis libero ultrices non. Donec sit amet dictum nisi, quis sodales turpis. Aliquam erat volutpat. Donec condimentum non arcu ut viverra. Vestibulum in egestas eros, ac ultrices est. Nulla consectetur vehicula mauris quis lacinia. Sed est mi, vestibulum eget suscipit nec, aliquet ac velit. Integer ut mauris ac nisl euismod congue.\n" +
                "\n" +
                "Mauris eget consequat libero. Integer vel orci eu risus porttitor consectetur ut aliquam nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris molestie dapibus arcu et tincidunt. Nunc sit amet nulla pellentesque, placerat metus ac, tempor nulla. Duis vestibulum velit vitae dolor iaculis, non mattis tortor convallis.\n" +
                "\n" +
                "Curabitur ac dui lorem. Cras interdum felis non lectus facilisis vulputate. Quisque in nunc semper, placerat nisi nec, consectetur ante. Integer sit amet mauris arcu. Nunc id dictum ipsum. Ut quis orci tortor. Etiam nulla nibh, condimentum finibus turpis mollis, ullamcorper scelerisque sem. Proin tellus lorem, molestie sit amet sodales nec, tempor non nunc.\n" +
                "\n" +
                "Aliquam aliquet neque sed erat ornare volutpat. Ut risus eros, molestie gravida efficitur vel, posuere eget nisi. Maecenas augue mi, aliquam sed tellus at, aliquam congue elit. Duis condimentum interdum magna sit amet volutpat. Phasellus et ipsum eleifend, lacinia nunc at, iaculis mi. Pellentesque non fermentum ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris vel laoreet eros, nec auctor arcu. Quisque in ante id sapien luctus scelerisque. Vivamus ornare, lectus quis aliquam rutrum, justo leo efficitur elit, sed tristique lacus lorem in enim. Etiam vel fringilla neque.\n" +
                "\n" +
                "Nunc quis risus risus. Integer a accumsan sapien, sed mollis lectus. Nulla vitae risus at felis molestie lacinia a eu sem. Sed vitae risus nec dolor viverra suscipit. Pellentesque feugiat pulvinar lorem, a interdum odio egestas a. Fusce dapibus quam lorem, non tincidunt orci sagittis eget. Nullam quis urna lacinia, vulputate turpis id, luctus sem. Proin cursus sollicitudin magna, congue consequat neque pulvinar eget. Quisque vel pulvinar orci. Vivamus ut cursus neque, a consequat augue. Etiam non risus vel ligula pharetra gravida.\n" +
                "\n" +
                "Vivamus ut tellus ultrices, consectetur odio quis, aliquam eros. Sed cursus ornare gravida. Aenean non condimentum leo. Donec tincidunt, est ultrices elementum condimentum, erat nulla tristique nibh, sed convallis dui tellus vel erat. Vivamus id urna volutpat, scelerisque tellus ac, tincidunt orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras vestibulum leo consectetur est pulvinar consectetur. Aenean et eros aliquam, efficitur diam a, feugiat turpis.\n" +
                "\n" +
                "Vestibulum id auctor lectus. Duis rutrum pretium justo ullamcorper egestas. Proin bibendum gravida odio, et aliquet odio sodales at. Vestibulum viverra mi vitae leo suscipit mollis eu sed urna. Donec ornare scelerisque velit ut eleifend. Nunc rhoncus quis magna et interdum. Donec suscipit venenatis elit, at scelerisque ex viverra eget. Nam facilisis nec ipsum a pellentesque. Aenean porttitor odio ac nisi mattis, ut condimentum erat sagittis. Cras tincidunt, tortor eget dignissim ultrices, nunc lorem fermentum sem, vitae porta nulla ligula eget ipsum. Integer egestas elit ex, ac efficitur elit fringilla vel. Cras euismod hendrerit justo, molestie fringilla purus convallis efficitur. Fusce fringilla sem in massa pharetra vehicula.\n" +
                "\n" +
                "Ut arcu augue, pulvinar ut commodo dignissim, ultrices sed sem. Nam mollis ut erat vel volutpat. Fusce id dolor finibus, posuere elit at, dapibus est. Etiam a neque at dui accumsan vestibulum at sed ex. Sed maximus euismod enim quis lobortis. Vivamus vitae euismod leo. Praesent eros urna, mollis quis eros et, mollis malesuada nibh. Donec in ipsum faucibus, luctus turpis in, sagittis eros. Aenean vel libero a ipsum dignissim pellentesque. Etiam congue mi sed libero ornare viverra. Nulla hendrerit viverra rutrum. Quisque placerat diam id commodo sodales. Cras vehicula mollis interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada eget ex quis vulputate. Aenean efficitur luctus mi, eget consequat urna tincidunt non.\n" +
                "\n" +
                "Vivamus mattis pretium mauris, nec aliquam felis congue gravida. Quisque suscipit et ligula eu ultrices. Praesent fermentum lectus elit, pulvinar mattis lacus aliquam eget. Aliquam elit quam, auctor posuere ullamcorper ac, rhoncus at elit. Pellentesque gravida id odio quis scelerisque. Nulla quis egestas libero. Cras pellentesque felis ex.\n" +
                "\n" +
                "Vivamus non arcu turpis. Aliquam a sollicitudin nisl. Morbi viverra sed tellus et varius. Praesent ante justo, elementum vel egestas eget, sodales et nibh. Quisque elementum enim id ante pulvinar, at tempus dolor vehicula. Vestibulum feugiat urna condimentum odio malesuada convallis. Aliquam ultricies sagittis rhoncus. Aliquam rutrum, erat id bibendum tempor, diam turpis tincidunt justo, gravida convallis enim eros elementum enim. Proin mattis dolor quis arcu vehicula porttitor. Duis volutpat diam eu est semper semper. Cras molestie, odio at eleifend luctus, diam nisi lacinia eros, vel facilisis ligula ligula ac nulla.\n" +
                "\n" +
                "Aliquam condimentum est eu hendrerit finibus. Nam non quam eu tortor dapibus cursus a non lectus. Nam ac dui molestie, mollis purus in, sollicitudin nisi. Curabitur tincidunt ornare lorem eget imperdiet. Nam semper pellentesque hendrerit. Fusce eu massa dolor. Donec in dolor magna. Integer vel tellus interdum, varius arcu sit amet, vulputate dui. Morbi ut tellus urna. Maecenas mollis ornare felis eu consequat. Proin rhoncus, lorem nec commodo efficitur, massa massa laoreet dolor, at viverra nibh nibh vel dolor. Suspendisse vestibulum aliquam neque, a venenatis lorem.\n" +
                "\n" +
                "Vivamus sed convallis nulla. Nam bibendum, mi vitae suscipit consequat, neque elit semper augue, ac consequat ipsum tortor at nisi. Proin non leo vel leo sagittis condimentum. Fusce cursus lacus rhoncus augue dapibus, vel laoreet ante faucibus. Nulla cursus quis purus non lobortis. Suspendisse potenti. Maecenas id mauris vitae enim pulvinar pretium eu a ex. Ut nulla tellus, semper ac venenatis ut, aliquet in velit. Phasellus lacinia posuere neque id pretium. Nulla tempus magna sed sem vestibulum pellentesque. Sed congue dui feugiat eros tempus porttitor non vel nisl. Vivamus accumsan neque a mauris porttitor, vel consectetur arcu suscipit. Curabitur mollis rhoncus molestie.\n" +
                "\n" +
                "Duis pharetra porttitor feugiat. Sed sed tortor et libero vulputate rutrum. Nullam efficitur velit nibh, vel interdum ex euismod sed. Nulla facilisi. Suspendisse eu bibendum sapien, ut rutrum eros. Nullam ornare lectus sit amet augue elementum, id pulvinar nulla ullamcorper. Proin pretium lectus nisi, id vulputate risus dictum a. Aenean at velit molestie, malesuada arcu eu, egestas massa.\n" +
                "\n" +
                "Nam maximus, diam vitae commodo vulputate, sem orci mollis mauris, vel dapibus massa diam eget libero. Vestibulum metus neque, luctus dapibus elit eu, fermentum efficitur erat. In elit urna, pretium sed diam nec, eleifend semper ante. Morbi consectetur malesuada augue in auctor. Aenean non commodo mauris. Suspendisse a ligula convallis dolor ullamcorper egestas. Etiam efficitur mollis libero, quis porttitor felis maximus ac. Cras molestie at dui a tempus. Morbi ligula mauris, facilisis non convallis non, volutpat in turpis.\n" +
                "\n" +
                "Aliquam ac scelerisque ligula. Nam eu ante id risus porta tristique. Nam rutrum lorem ut tincidunt venenatis. Aenean tristique ipsum nec molestie rutrum. Phasellus efficitur, arcu non mattis viverra, augue odio dictum risus, nec lacinia nisi urna egestas risus. Pellentesque ultricies mauris pretium sem accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam tincidunt lorem id odio semper viverra.\n" +
                "\n" +
                "Fusce sed nisi malesuada nibh lacinia ultricies. Aenean suscipit augue a semper eleifend. Sed sed tempus ex. In quis mi lacus. Donec iaculis sollicitudin interdum. Fusce pellentesque vehicula sodales. Mauris feugiat nulla non nisl maximus tempor. In ac porttitor lorem. Donec tempor, justo auctor finibus gravida, sapien turpis fermentum tellus, quis rutrum metus urna ac neque. In hac habitasse platea dictumst. Vestibulum tempor sagittis orci, in rhoncus libero vehicula id. In eget hendrerit purus. Morbi at mi feugiat, aliquam libero ut, viverra tellus. Fusce finibus finibus purus, in efficitur sapien viverra quis.\n" +
                "\n" +
                "Cras accumsan cursus arcu eleifend tristique. Phasellus egestas dui id turpis accumsan facilisis. Nullam euismod, turpis eu venenatis faucibus, turpis leo vehicula lacus, nec aliquet ligula odio et mauris. Maecenas imperdiet bibendum mi, non mollis magna porttitor et. Nullam a elit nec justo volutpat venenatis. Aenean quis sapien et nisl interdum volutpat in sit amet nisl. Morbi finibus, dolor nec sollicitudin varius, elit lacus hendrerit lectus, sed vehicula libero magna in elit. Ut porttitor metus at libero auctor fermentum. Sed quis metus ex. Sed eu sapien aliquam, lobortis dui ut, pharetra mauris. Fusce efficitur facilisis purus. Praesent dictum elit ac scelerisque rutrum. Duis nibh ipsum, euismod rutrum rhoncus ac, congue ac velit. Sed magna dolor, iaculis id nisi et, consectetur mattis felis. Nunc vestibulum eros et enim mattis dictum.\n" +
                "\n" +
                "Aliquam elementum mauris eget tristique rhoncus. In vitae nisi consectetur, condimentum dolor quis, consequat metus. Donec tincidunt eu diam nec pellentesque. Proin sit amet molestie elit, ut maximus lacus. Etiam quis viverra sapien. Integer fringilla sed erat at tempor. Curabitur pharetra euismod leo, quis imperdiet nisl facilisis vel. Maecenas dignissim ipsum non ante elementum, vitae consequat turpis feugiat. Curabitur varius tempus malesuada. Quisque tincidunt, nisi viverra efficitur porttitor, est lorem faucibus orci, id lobortis libero leo ut arcu. Nunc malesuada ultricies cursus. Suspendisse sit amet urna interdum, volutpat risus ac, sagittis elit.\n" +
                "\n" +
                "Fusce sollicitudin hendrerit arcu id pellentesque. Sed malesuada augue quis ante convallis blandit. In hac habitasse platea dictumst. Donec risus erat, egestas ac scelerisque at, porta sit amet enim. Suspendisse vel mauris id quam fringilla malesuada eget sed nibh. Curabitur at purus maximus tortor consequat congue. Cras lacus justo, vulputate non enim nec, commodo ullamcorper risus. Aenean egestas dolor feugiat, malesuada mauris sed, scelerisque arcu. Nulla sapien lectus, porta quis malesuada in, ullamcorper at est. Aenean quis nibh ut quam cursus sollicitudin. Nullam efficitur egestas neque, non tristique metus vulputate eget. Mauris vestibulum, ex id molestie pretium, dolor turpis porta orci, eu sodales arcu magna eu felis. Suspendisse vitae nulla neque.\n" +
                "\n" +
                "Vestibulum sit amet tellus ut tortor ullamcorper convallis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porta, dolor ac ornare vehicula, arcu lorem consequat mauris, id sagittis tellus ex vel sem. Phasellus vitae tincidunt magna, ac lobortis tortor. Nam orci leo, pretium id leo id, blandit viverra lectus. Suspendisse id purus orci. Sed suscipit turpis eget volutpat convallis. Ut ultricies sodales urna in mollis. Mauris nunc libero, viverra elementum rutrum eget, consequat et nibh. Donec sit amet nibh lacus. Donec quis orci sapien. Fusce volutpat sollicitudin pretium. Cras ac lacus velit. Curabitur scelerisque mi bibendum tortor convallis, non varius quam suscipit. Aenean convallis sagittis libero eget aliquam.\n" +
                "\n" +
                "Nulla sit amet lacinia sem. Aenean sed est iaculis, egestas lectus id, iaculis felis. In hac habitasse platea dictumst. Cras dui mi, euismod a sodales quis, sodales ac justo. Sed arcu nisl, luctus ac lacinia sed, sollicitudin id magna. Maecenas quis ligula arcu. Etiam imperdiet tortor ipsum, ut volutpat neque finibus quis. Aliquam fermentum turpis sed nulla dapibus, ac semper orci sollicitudin. Vestibulum condimentum arcu ut malesuada feugiat. Mauris sit amet purus enim. Nullam augue risus, fermentum efficitur ipsum et, posuere volutpat mi. Praesent posuere ornare sapien auctor suscipit. Proin eu ex convallis, lobortis est et, pretium lacus. Mauris sagittis lacus in augue volutpat suscipit. Cras aliquam varius elit ut facilisis.\n" +
                "\n" +
                "Praesent luctus, quam eget porttitor posuere, felis est aliquam tortor, ut scelerisque dolor neque a massa. Praesent rhoncus sodales nunc nec mattis. Donec suscipit justo ligula, dapibus euismod dui tempus rutrum. Ut maximus facilisis orci et porta. In ac blandit urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pulvinar felis dolor, ac semper nulla interdum nec. Donec tempus ligula libero, nec volutpat nibh dapibus sit amet. Cras condimentum ligula at posuere maximus. Nulla porta convallis sapien et malesuada. Fusce pretium arcu non laoreet feugiat. Aenean nisi est, commodo eu enim non, blandit posuere erat. Ut a iaculis dui.\n" +
                "\n" +
                "Aenean sed tortor pellentesque, placerat ipsum blandit, ultricies diam. Phasellus vitae odio odio. Etiam interdum mi mi, eu luctus justo interdum vel. Suspendisse consequat massa a tellus suscipit interdum. Sed eget ante magna. Integer at leo sem. Nunc et leo at magna convallis vulputate. Nam elementum magna ligula, sit amet laoreet dui varius eget. Sed at euismod tortor, eget viverra massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus a dapibus tellus. In vel nibh ligula. Donec eleifend elit nec mi malesuada varius. Phasellus ultricies, massa in rhoncus dignissim, odio ligula convallis est, ut sodales lectus risus ornare augue. Donec turpis dui, accumsan eget elit eget, ullamcorper pharetra metus.\n" +
                "\n" +
                "Sed imperdiet felis sit amet metus condimentum, non tempor dolor consectetur. Mauris scelerisque nisl ac nulla aliquet, eu euismod nunc tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean blandit, turpis in commodo tempor, tellus ligula condimentum nibh, ut luctus elit lorem a tellus. Duis tempor arcu eget est sagittis tincidunt. Nulla at sem non ipsum tristique semper sit amet sit amet justo. In a sapien quis ante accumsan volutpat. Mauris hendrerit diam in sodales iaculis.\n" +
                "\n" +
                "In hac habitasse platea dictumst. Sed ut ullamcorper massa, id tempus ex. Curabitur vel semper mi, aliquet dictum nisi. Proin elementum gravida orci, non scelerisque metus commodo non. Proin tempus tortor et interdum eleifend. Donec lacinia vitae nibh cursus venenatis. Proin dui lorem, sollicitudin ut rutrum ac, aliquet sed nulla. Donec sollicitudin, velit non euismod convallis, quam mauris dignissim magna, in aliquet mi lacus vel lacus. Integer bibendum malesuada nibh, non lacinia nunc vulputate eget. Nullam posuere nec felis a eleifend. Donec fermentum fringilla libero ut molestie. Quisque sed condimentum mauris. Etiam a eleifend leo. Vivamus pulvinar dignissim justo. Vivamus consectetur eleifend placerat. Pellentesque at porttitor nunc.\n" +
                "\n" +
                "Nullam tincidunt nulla ipsum, auctor finibus tellus dictum vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ut leo id lorem facilisis venenatis ac tempus justo. Etiam sapien dui, interdum eu magna bibendum, pellentesque imperdiet arcu. Donec eu ante eu sem sollicitudin tempor sit amet varius tortor. Proin non eleifend risus, eu ornare mauris. Quisque sed egestas tortor. Pellentesque in ex leo. Cras venenatis, orci eget interdum pretium, nunc metus interdum ante, eget feugiat nibh mauris non massa. Mauris placerat accumsan tristique. Aliquam et lectus odio. Ut eget feugiat libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc lobortis arcu neque, vitae blandit nunc scelerisque hendrerit.\n" +
                "\n" +
                "Nullam lobortis ligula id magna tristique scelerisque. Etiam sagittis magna id ornare convallis. Fusce cursus sapien quis risus placerat feugiat. Vivamus suscipit enim nec ultricies vulputate. Ut cursus eros nec lacinia vulputate. Phasellus varius et justo a suscipit. Proin mollis est vulputate lacinia suscipit. Nam eget iaculis quam. Cras sapien felis, suscipit tempus gravida sed, commodo in risus. Sed at turpis vitae tellus auctor cursus. Duis tristique dignissim mi, vel sodales dui tincidunt nec. Pellentesque sit amet justo ex. Vestibulum purus nulla, lacinia et odio dapibus, ultricies laoreet turpis. Mauris sollicitudin consectetur dolor, in accumsan nulla elementum in. Nunc blandit nisl a porta feugiat. Fusce sit amet ornare augue, id hendrerit metus.\n" +
                "\n" +
                "Mauris luctus elit ac dui bibendum, sit amet aliquet nisl ultrices. Suspendisse pretium, diam eget consectetur faucibus, enim leo rutrum risus, et accumsan felis turpis non enim. Duis efficitur massa lorem, at varius mi feugiat eget. Vivamus pellentesque porttitor pellentesque. Maecenas auctor rutrum bibendum. In dignissim tortor arcu, cursus elementum ipsum efficitur bibendum. Phasellus risus nulla, vulputate vel augue ac, feugiat commodo turpis.\n" +
                "\n" +
                "Fusce laoreet efficitur tellus, non dapibus justo semper in. Sed viverra leo a rhoncus dictum. Phasellus eros libero, sollicitudin ut porttitor et, auctor et nibh. Ut nec efficitur enim, laoreet laoreet nibh. Nullam ullamcorper ultrices nibh in accumsan. Phasellus sagittis scelerisque mauris, id elementum sem aliquet vel. Vivamus lacinia dictum pretium.\n" +
                "\n" +
                "Curabitur quis egestas tortor. Duis tincidunt odio vel varius aliquet. Sed bibendum ligula dolor, non finibus quam pharetra vitae. Aenean bibendum, nulla vel pulvinar condimentum, lacus erat vulputate ligula, at mollis neque tellus id dolor. Nulla eu neque dolor. Sed id magna porta, egestas erat eget, egestas lorem. Curabitur tempus maximus tortor nec vehicula. Aliquam non suscipit nisi. Aenean ornare consectetur mauris, vitae interdum arcu dictum ut. Sed maximus quam congue dolor hendrerit mattis ac eget magna. Cras erat diam, elementum nec ex a, vehicula posuere lorem. In ullamcorper eget nisl a posuere. Maecenas varius sed sem vitae maximus. Fusce feugiat ullamcorper metus. Ut pulvinar nunc eu maximus convallis.\n" +
                "\n" +
                "In feugiat magna ut mauris bibendum scelerisque. Suspendisse porttitor lorem quis lobortis ullamcorper. Mauris fringilla nunc libero, sed aliquet massa finibus sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus pellentesque, sem vel laoreet mollis, augue metus vestibulum urna, non venenatis nibh libero sed turpis. Fusce rutrum tellus ac venenatis finibus. Aliquam leo ipsum, maximus eget faucibus ut, sagittis eget ligula. Nullam quis felis venenatis, consectetur ex ut, imperdiet elit.\n" +
                "\n" +
                "Ut faucibus sagittis turpis, id hendrerit erat lobortis sit amet. Suspendisse bibendum facilisis justo, eget aliquet dui aliquam id. Aliquam arcu ligula, consequat eleifend lorem ac, dictum ullamcorper turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget nisl sit amet dolor dictum tristique. Integer quis ornare risus. Donec vel lacinia orci, id facilisis sapien. Vivamus tempor mollis interdum. Nulla scelerisque eget metus et auctor. Sed semper mi nec est tincidunt ultricies. Phasellus consequat neque purus, ut vehicula lectus finibus nec. Nulla facilisis purus tortor, ac rhoncus nibh maximus non.\n" +
                "\n" +
                "Donec eu dignissim est. Sed sit amet elementum urna. Suspendisse ac ipsum sed ante tincidunt pharetra. Mauris feugiat porttitor varius. Duis at purus lorem. Donec tincidunt non dolor ac pulvinar. Aenean rutrum sem non felis fringilla hendrerit eu et ipsum. Donec ultrices odio sed erat varius mollis. Aenean pulvinar ac lectus sit amet feugiat. Suspendisse congue ultrices ligula vel luctus.\n" +
                "\n" +
                "Nam dapibus porta nibh vel vestibulum. Pellentesque imperdiet, enim vitae venenatis tempus, tortor urna tristique sapien, nec euismod massa urna quis diam. Donec vestibulum mauris id purus suscipit, vitae scelerisque dolor ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla hendrerit dignissim velit, ullamcorper consectetur libero viverra sed. Pellentesque bibendum quam a ligula faucibus, quis pellentesque neque blandit. Integer gravida lacinia luctus. Nam a mi porta, commodo dolor in, suscipit est. Duis vel porta nisi. Pellentesque leo lacus, cursus sit amet feugiat et, hendrerit id tellus. Morbi sit amet odio imperdiet, consequat nulla id, consequat neque. Vestibulum id tortor dictum, semper lectus et, gravida enim.");
    }
}
